##### NumPy is an open source library available in Python that aids in mathematical, scientific, engineering, and data science programming. NumPy is an incredible library to perform mathematical and statistical operations. It works perfectly well for multi-dimensional arrays and matrices multiplication 

In [0]:
#run cmd commands in jupyter using ! 
!pip install numpy

### Other ways of installing through CMD
##### python -m pip install numpy
##### pip install numpy 

In [0]:
import numpy as np

#### Creating numpy array using list 

In [0]:
a = [1, 2, 3, 4, 5, 6]
npar = np.array(a)

In [0]:
npar

array([1, 2, 3, 4, 5, 6])

In [0]:
nparr = np.array([1, 2, 3, 4])
nparr

array([1, 2, 3, 4])

In [0]:
npa1 = np.array([[1,2,3], [4,5,6], [6,8,9]])
npa1

array([[1, 2, 3],
       [4, 5, 6],
       [6, 8, 9]])

#### Creating array using np.random 

##### Return random integers from low (inclusive) to high (exclusive).Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). 

In [0]:
a = np.random.randint(10, size=6)  
b = np.random.randint(10, size=(2, 3))  
c = np.random.randint(10, size=(2, 3, 4))  

In [0]:
a

array([2, 2, 1, 4, 2, 0])

In [0]:
b

array([[7, 0, 9],
       [0, 0, 5]])

In [0]:
c

array([[[4, 8, 6, 0],
        [0, 5, 6, 1],
        [1, 6, 6, 9]],

       [[8, 9, 2, 1],
        [4, 8, 5, 5],
        [5, 6, 3, 0]]])

#### Creating using np.arrange 

##### Return evenly spaced values within a given interval.Values are generated within the half-open interval [start, stop)

In [0]:
# Values from 0 to 4(exclusive) with default start as 0
a1 = np.arange(4)

# Values from 0 to 6.0(exclusive) with default start as 0.0
a2 = np.arange(6.0)

# Values between 6 and 15 with defualt step of 1 
a3 = np.arange(6,15)

# Values between 3 and 10(exclusive), with step 2
a4 = np.arange(3,10,2)

In [0]:
a1

array([0, 1, 2, 3])

In [0]:
a2

array([0., 1., 2., 3., 4., 5.])

In [0]:
a3

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
a4

array([3, 4, 5, 6, 7, 8, 9])

#### Minimum dimension

In [0]:
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], ndmin=3)

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [0]:
np.array([1, 2, 3, 4, 5, 6], ndmin=2)

array([[1, 2, 3, 4, 5, 6]])

#### Data type of array 

In [0]:
f = np.array([5.7, 8.9, 4])
f

array([5.7, 8.9, 4. ])

In [0]:
np.array(f, dtype=np.int, copy=True, order='K', subok=False, ndmin=0)

array([5, 8, 4])

In [0]:
np.array(f, dtype = complex)

array([5.7+0.j, 8.9+0.j, 4. +0.j])

In [0]:
c = np.array([[1,2,3], [4,5,6,]], dtype = complex)

In [0]:
c.shape

(2, 3)

In [0]:
c.dtype

dtype('complex128')

#### Reshaping array 

In [0]:
c.shape

(3, 2)

In [0]:
c.shape = (2,3)

In [0]:
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [0]:
g = np.arange(3,20,2)
print(g.ndim)
print(g.shape)
print(g)

1
(9,)
[ 3  5  7  9 11 13 15 17 19]


In [0]:
h = g.reshape(3,3)
print(h.ndim)
print(h.shape)
print(h)

2
(3, 3)
[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]]


#### Difference between ndim, shape and size

In [0]:
d = np.random.randint(3, 10, size = (2, 3, 4))

In [0]:
# Gives the dimensions of the array..
print("d ndim: ", d.ndim)

# Gives the no. of rows and columns (if any) of the array
print("d shape:", d.shape)

# Gives the total no. of elements in the array 
print("d size: ", d.size)

d ndim:  3
d shape: (2, 3, 4)
d size:  24


In [0]:
# Gives the size of each element in array in  bytes
print("itemsize:", d.itemsize, "bytes")

# Gives the total size of array in bytes 
print("nbytes:", d.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 96 bytes


#### Using np.empty

##### Return a new array of given shape and type, without initializing entries.

In [0]:
# The elements are random values and by default the datatype is float
np.empty([2, 2])

array([[1.44058144e-311, 1.44061652e-311],
       [1.44058840e-311, 2.96439388e-323]])

In [0]:
np.empty([2, 2], dtype=int)

array([[3, 5],
       [7, 9]])

#### Using np.zeroes()

###### Return a new array of given shape and type, filled with zeros.

In [0]:
np.zeros(6)

array([0., 0., 0., 0., 0.])

In [0]:
np.zeros((3,), dtype=int)

array([0, 0, 0])

In [0]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.zeros((3,), dtype=[('a', 'i4'), ('b', 'i4')]) # custom dtype

array([(0, 0), (0, 0), (0, 0)], dtype=[('a', '<i4'), ('b', '<i4')])

#### Using np.ones()

##### Return a new array of given shape and type, filled with ones.

In [0]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [0]:
np.ones((3,), dtype=int)

array([1, 1, 1])

In [0]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Using np.asarray()

##### Convert the input to an array.Similar to np.array with fewer parameters 

In [0]:
a = np.array([3, 2, 5, 6, 8, 9])
a

array([3, 2, 5, 6, 8, 9])

In [0]:
b = np.array([1, 2, 6, 9, 10], dtype=np.float32)
b

array([ 1.,  2.,  6.,  9., 10.], dtype=float32)

In [0]:
# Datatypes are diff, so 'is' operator returns False 
np.asarray(b, dtype=np.float64) is b

False

#### Using np.linspace()

##### Returns num evenly spaced samples, calculated over the interval [start, stop].

In [0]:
# Returns 5 numbers between 10 and 40 that are equally spaced 
np.linspace(10, 40, 5)

array([10. , 17.5, 25. , 32.5, 40. ])

In [0]:
# If True, return (samples, step), where step is the spacing between samples.
np.linspace(2.0, 10.0, 6, retstep=True)

(array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ]), 1.6)

In [0]:
# If endpoint is False, then the stoping values in not included, 
#by default its True
np.linspace(2.0, 10.0, 6, endpoint=False, retstep=True)

(array([2.        , 3.33333333, 4.66666667, 6.        , 7.33333333,
        8.66666667]), 1.3333333333333333)

#### Slicing and Indexing 

In [0]:
a = np.arange(10, 30, 2) 
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [0]:
# Start slicing from 2 to 7(exclusive) with step 2
s = slice(2,11,2) 
a[s]

array([14, 18, 22, 26])

In [0]:
#another way of slicing without slice function 
a[2:11:2]

array([14, 18, 22, 26])

In [0]:
# Starting from 10(exclusive) reverse indexing till -5 with step 2
a[-5:10:2]

array([20, 24, 28])

In [0]:
# Starting from 10(exclusive) reverse indexing till -5 with step 2
a[-9:10:1]

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [0]:
# Accessing through indices 
print(a[2])
print(a[5])

14
20


In [0]:
a[:5]

array([10, 12, 14, 16, 18])

In [0]:
a[5:]

array([20, 22, 24, 26, 28])

In [0]:
a[2:8]

array([14, 16, 18, 20, 22, 24])

In [0]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x.shape

(2, 3, 1)

In [0]:
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [0]:
 x[1:2]

array([[[4],
        [5],
        [6]]])

#### Advanced Indexing 

##### There are two types of advanced indexing: integer and Boolean.Advanced indexing always returns a copy of the data (contrast with basic slicing that returns a view).

#### Integer indexing

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [0]:
# [0, 1, 2] represnt the row numbers to select from, 
#then [1, 2, 1] represnts the column elemnts to select from each row
#We select 3 elements in this way. 

#From 0th row, we are selecting 1st element i.e 2, from 1st row,
#we are selecting 2nd element i.e 6 and so on.
x[[0, 1, 2], [1, 2, 1]]

array([2, 6, 8])

In [0]:
x = np.array([[ 0,  1,  2],
    [ 3,  4,  5],
    [ 6,  7,  8],
    [ 9, 10, 11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
rows = np.array([[0, 0],
                  [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                   [0, 2]], dtype=np.intp)

In [0]:
rows

array([[0, 0],
       [3, 3]], dtype=int64)

In [0]:
columns

array([[0, 2],
       [0, 2]], dtype=int64)

In [0]:
x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

#### Boolean Indexing

In [0]:
rowsum = x.sum(-1)
x[rowsum >= 5, :]

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
x[x>7]

array([ 8,  9, 10, 11])

#### String Operations

In [0]:
np.char.add(['hello'],[' hrc']) 

array(['hello hrc'], dtype='<U9')

In [0]:
np.char.add(['Hey', 'Hi'],[' HRC', ' KIIT'])

array(['Hey HRC', 'Hi KIIT'], dtype='<U8')

In [0]:
np.char.multiply('Hey ',3)

array('Hey Hey Hey ', dtype='<U12')

In [0]:
np.char.center('highradius', 20,fillchar = '*')

array('*****highradius*****', dtype='<U20')

In [0]:
np.char.capitalize('welcome to kiit')

array('Welcome to kiit', dtype='<U15')

In [0]:
np.char.lower(['INDIA','PAKISTAN']) 

array(['india', 'pakistan'], dtype='<U8')

In [0]:
np.char.upper('india') 

array('INDIA', dtype='<U5')

In [0]:
np.char.split ('hello how are you?') 

array(list(['hello', 'how', 'are', 'you?']), dtype=object)

In [0]:
np.char.strip(['aighradius','company','java'],'a')

array(['ighradius', 'company', 'jav'], dtype='<U10')

In [0]:
np.char.strip('ashok arora','a') 

array('shok aror', dtype='<U11')

In [0]:
np.char.join(':','dmy') 

array('d:m:y', dtype='<U5')

In [0]:
np.char.join([':','-'],['dmy','ymd'])

array(['d:m:y', 'y-m-d'], dtype='<U5')

In [0]:
np.char.replace ("I'm a good person", 'good', 'bad')

array("I'm a bad person", dtype='<U16')

#### Mathematical Operations

In [0]:
a = np.array([1.0, 59.55, 126, 0.567, 65.532]) 
a

array([  1.   ,  59.55 , 126.   ,   0.567,  65.532])

In [0]:
np.around(a) 

array([  1.,  60., 126.,   1.,  66.])

In [0]:
np.around(a, decimals = 1) 


array([  1. ,  59.6, 126. ,   0.6,  65.5])

In [0]:
np.around(a, decimals = -1)

array([  0.,  60., 130.,   0.,  70.])

In [0]:
a = np.array([-1.7, 1.5, -0.2, 0.6, 10]) 
a

array([-1.7,  1.5, -0.2,  0.6, 10. ])

In [0]:
np.floor(a)

array([-2.,  1., -1.,  0., 10.])

In [0]:
np.ceil(a)

array([-1.,  2., -0.,  1., 10.])

#### Arithmetical Operations and linear Algebra

In [0]:
a = np.array([0.25, 1.33, 1, 0, 100]) 

In [0]:
np.reciprocal(a)

E:\sahiti.krishna\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.


array([4.       , 0.7518797, 1.       ,       inf, 0.01     ])

In [0]:
b = np.array([100], dtype = int) 
b

array([100])

In [0]:
np.reciprocal(b) 

array([0], dtype=int32)

In [0]:
a = np.array([2, 3, 5, 0, 100]) 

In [0]:
np.power(a,2)

array([    4,     9,    25,     0, 10000], dtype=int32)

In [0]:
a = np.array([10,20,30]) 
b = np.array([3,5,7]) 

In [0]:
np.mod(a,b) 

array([1, 0, 2], dtype=int32)

In [0]:
a = np.array([-5.6j, 0.2j, 11. , 1+1j])
a

array([-0.-5.6j,  0.+0.2j, 11.+0.j ,  1.+1.j ])

In [0]:
np.real(a)

array([-0.,  0., 11.,  1.])

In [0]:
np.imag(a) 

array([-5.6,  0.2,  0. ,  1. ])

In [0]:
np.conj(a)

array([-0.+5.6j,  0.-0.2j, 11.-0.j ,  1.-1.j ])

In [0]:
np.angle(a, deg = True)

array([-90.,  90.,   0.,  45.])

In [0]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [0]:
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
np.matmul(a,b)

array([[4, 1],
       [2, 2]])

In [0]:
a = np.arange(8).reshape(2,2,2) 
b = np.arange(4).reshape(2,2) 
np.matmul(a,b)

array([[[ 2,  3],
        [ 6, 11]],

       [[10, 19],
        [14, 27]]])

In [0]:
a = np.array([[1,2], [3,4]]) 
np.linalg.det(a)

-2.0000000000000004